/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.UNO_DamienCantinImpl <em>UNO Damien Cantin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.UNO_DamienCantinImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getUNO_DamienCantin()
   * @generated
   */
  int UNO_DAMIEN_CANTIN = 0;

  /**
   * The feature id for the '<em><b>Uno</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_DAMIEN_CANTIN__UNO = 0;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_DAMIEN_CANTIN__VAR = 1;

  /**
   * The feature id for the '<em><b>Base</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_DAMIEN_CANTIN__BASE = 2;

  /**
   * The feature id for the '<em><b>Variants</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_DAMIEN_CANTIN__VARIANTS = 3;

  /**
   * The number of structural features of the '<em>UNO Damien Cantin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNO_DAMIEN_CANTIN_FEATURE_COUNT = 4;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.UNO_DamienCantin <em>UNO Damien Cantin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>UNO Damien Cantin</em>'.
   * @see org.xtext.example.mydsl.myDsl.UNO_DamienCantin
   * @generated
   */
  EClass getUNO_DamienCantin();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.UNO_DamienCantin#getUno <em>Uno</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Uno</em>'.
   * @see org.xtext.example.mydsl.myDsl.UNO_DamienCantin#getUno()
   * @see #getUNO_DamienCantin()
   * @generated
   */
  EAttribute getUNO_DamienCantin_Uno();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.UNO_DamienCantin#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see org.xtext.example.mydsl.myDsl.UNO_DamienCantin#getVar()
   * @see #getUNO_DamienCantin()
   * @generated
   */
  EAttribute getUNO_DamienCantin_Var();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.UNO_DamienCantin#getBase <em>Base</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Base</em>'.
   * @see org.xtext.example.mydsl.myDsl.UNO_DamienCantin#getBase()
   * @see #getUNO_DamienCantin()
   * @generated
   */
  EAttribute getUNO_DamienCantin_Base();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.UNO_DamienCantin#getVariants <em>Variants</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Variants</em>'.
   * @see org.xtext.example.mydsl.myDsl.UNO_DamienCantin#getVariants()
   * @see #getUNO_DamienCantin()
   * @generated
   */
  EAttribute getUNO_DamienCantin_Variants();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.UNO_DamienCantinImpl <em>UNO Damien Cantin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.UNO_DamienCantinImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getUNO_DamienCantin()
     * @generated
     */
    EClass UNO_DAMIEN_CANTIN = eINSTANCE.getUNO_DamienCantin();

    /**
     * The meta object literal for the '<em><b>Uno</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_DAMIEN_CANTIN__UNO = eINSTANCE.getUNO_DamienCantin_Uno();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_DAMIEN_CANTIN__VAR = eINSTANCE.getUNO_DamienCantin_Var();

    /**
     * The meta object literal for the '<em><b>Base</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_DAMIEN_CANTIN__BASE = eINSTANCE.getUNO_DamienCantin_Base();

    /**
     * The meta object literal for the '<em><b>Variants</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNO_DAMIEN_CANTIN__VARIANTS = eINSTANCE.getUNO_DamienCantin_Variants();

  }

} //MyDslPackage
