/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>UNO Damien Cantin</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.UNO_DamienCantin#getUno <em>Uno</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.UNO_DamienCantin#getVar <em>Var</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.UNO_DamienCantin#getBase <em>Base</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.UNO_DamienCantin#getVariants <em>Variants</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getUNO_DamienCantin()
 * @model
 * @generated
 */
public interface UNO_DamienCantin extends EObject
{
  /**
   * Returns the value of the '<em><b>Uno</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uno</em>' attribute.
   * @see #setUno(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getUNO_DamienCantin_Uno()
   * @model
   * @generated
   */
  String getUno();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.UNO_DamienCantin#getUno <em>Uno</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Uno</em>' attribute.
   * @see #getUno()
   * @generated
   */
  void setUno(String value);

  /**
   * Returns the value of the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' attribute.
   * @see #setVar(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getUNO_DamienCantin_Var()
   * @model
   * @generated
   */
  String getVar();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.UNO_DamienCantin#getVar <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' attribute.
   * @see #getVar()
   * @generated
   */
  void setVar(String value);

  /**
   * Returns the value of the '<em><b>Base</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base</em>' attribute.
   * @see #setBase(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getUNO_DamienCantin_Base()
   * @model
   * @generated
   */
  String getBase();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.UNO_DamienCantin#getBase <em>Base</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base</em>' attribute.
   * @see #getBase()
   * @generated
   */
  void setBase(String value);

  /**
   * Returns the value of the '<em><b>Variants</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variants</em>' attribute.
   * @see #setVariants(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getUNO_DamienCantin_Variants()
   * @model
   * @generated
   */
  String getVariants();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.UNO_DamienCantin#getVariants <em>Variants</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variants</em>' attribute.
   * @see #getVariants()
   * @generated
   */
  void setVariants(String value);

} // UNO_DamienCantin
