/**
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.UNO_DamienCantin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>UNO Damien Cantin</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.UNO_DamienCantinImpl#getUno <em>Uno</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.UNO_DamienCantinImpl#getVar <em>Var</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.UNO_DamienCantinImpl#getBase <em>Base</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.UNO_DamienCantinImpl#getVariants <em>Variants</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UNO_DamienCantinImpl extends MinimalEObjectImpl.Container implements UNO_DamienCantin
{
  /**
   * The default value of the '{@link #getUno() <em>Uno</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUno()
   * @generated
   * @ordered
   */
  protected static final String UNO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getUno() <em>Uno</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUno()
   * @generated
   * @ordered
   */
  protected String uno = UNO_EDEFAULT;

  /**
   * The default value of the '{@link #getVar() <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar()
   * @generated
   * @ordered
   */
  protected static final String VAR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVar() <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar()
   * @generated
   * @ordered
   */
  protected String var = VAR_EDEFAULT;

  /**
   * The default value of the '{@link #getBase() <em>Base</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBase()
   * @generated
   * @ordered
   */
  protected static final String BASE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBase() <em>Base</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBase()
   * @generated
   * @ordered
   */
  protected String base = BASE_EDEFAULT;

  /**
   * The default value of the '{@link #getVariants() <em>Variants</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariants()
   * @generated
   * @ordered
   */
  protected static final String VARIANTS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVariants() <em>Variants</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariants()
   * @generated
   * @ordered
   */
  protected String variants = VARIANTS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UNO_DamienCantinImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.UNO_DAMIEN_CANTIN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getUno()
  {
    return uno;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUno(String newUno)
  {
    String oldUno = uno;
    uno = newUno;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.UNO_DAMIEN_CANTIN__UNO, oldUno, uno));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVar()
  {
    return var;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVar(String newVar)
  {
    String oldVar = var;
    var = newVar;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.UNO_DAMIEN_CANTIN__VAR, oldVar, var));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getBase()
  {
    return base;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBase(String newBase)
  {
    String oldBase = base;
    base = newBase;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.UNO_DAMIEN_CANTIN__BASE, oldBase, base));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVariants()
  {
    return variants;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVariants(String newVariants)
  {
    String oldVariants = variants;
    variants = newVariants;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.UNO_DAMIEN_CANTIN__VARIANTS, oldVariants, variants));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.UNO_DAMIEN_CANTIN__UNO:
        return getUno();
      case MyDslPackage.UNO_DAMIEN_CANTIN__VAR:
        return getVar();
      case MyDslPackage.UNO_DAMIEN_CANTIN__BASE:
        return getBase();
      case MyDslPackage.UNO_DAMIEN_CANTIN__VARIANTS:
        return getVariants();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.UNO_DAMIEN_CANTIN__UNO:
        setUno((String)newValue);
        return;
      case MyDslPackage.UNO_DAMIEN_CANTIN__VAR:
        setVar((String)newValue);
        return;
      case MyDslPackage.UNO_DAMIEN_CANTIN__BASE:
        setBase((String)newValue);
        return;
      case MyDslPackage.UNO_DAMIEN_CANTIN__VARIANTS:
        setVariants((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.UNO_DAMIEN_CANTIN__UNO:
        setUno(UNO_EDEFAULT);
        return;
      case MyDslPackage.UNO_DAMIEN_CANTIN__VAR:
        setVar(VAR_EDEFAULT);
        return;
      case MyDslPackage.UNO_DAMIEN_CANTIN__BASE:
        setBase(BASE_EDEFAULT);
        return;
      case MyDslPackage.UNO_DAMIEN_CANTIN__VARIANTS:
        setVariants(VARIANTS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.UNO_DAMIEN_CANTIN__UNO:
        return UNO_EDEFAULT == null ? uno != null : !UNO_EDEFAULT.equals(uno);
      case MyDslPackage.UNO_DAMIEN_CANTIN__VAR:
        return VAR_EDEFAULT == null ? var != null : !VAR_EDEFAULT.equals(var);
      case MyDslPackage.UNO_DAMIEN_CANTIN__BASE:
        return BASE_EDEFAULT == null ? base != null : !BASE_EDEFAULT.equals(base);
      case MyDslPackage.UNO_DAMIEN_CANTIN__VARIANTS:
        return VARIANTS_EDEFAULT == null ? variants != null : !VARIANTS_EDEFAULT.equals(variants);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (uno: ");
    result.append(uno);
    result.append(", var: ");
    result.append(var);
    result.append(", base: ");
    result.append(base);
    result.append(", variants: ");
    result.append(variants);
    result.append(')');
    return result.toString();
  }

} //UNO_DamienCantinImpl
